### ISSUE TITLE
`$=toc` shows `as is` in index page

### ISSUE THREAD

**Issue by 4mig4** [Fizzadar/Luapress#75]
LuaPress 4.0

`$=toc` shows as is (not interpretation is done) in `index page` list,  when looking at the article `$=toc` is correctly interpred and the TOC is built.

Probably the `$=toc` should be ignored in the `index page`.

**Comment by 4mig4** [comment]
Probably you also did not notice this issue as well.

**Comment by Fizzadar** [comment]
@4mig4 `$=toc` is working as expected on pages from my end - eg on luapress.org (https://github.com/Fizzadar/luapress.org/blob/develop/templates/luapress/header.mustache#L21).

What does the page copy look like?

**Comment by 4mig4** [comment]
`$=toc` shows uninterpreted in the `index page` list if inserted at the top ( before the --MORE--)

![test](https://user-images.githubusercontent.com/3671074/60778903-c29eaa80-a173-11e9-8cbe-bd5db52198b5.png)

```
$title=Test
$date=08/07/2019
$location=Somewhere, On Earth
$=toc

This is just a test

--MORE--

blabla
```

**Comment by 4mig4** [comment]
I corrected my ambiguous descriptions of the problem. It is the `index page` that is affected and not the `post page` itself.

**Comment by Fizzadar** [comment]
@4mig4 it looks like this is because there is no valid TOC - the markdown contains no headers so no TOC is generated/replaced.

I'll change it so that the `$=toc` is be removed in this case; rather than left in position.

**Comment by Fizzadar** [comment]
This should be fixed by https://github.com/Fizzadar/Luapress/commit/ef6b490bf07994bec0c4c7f96be9158d9e548b37 - will release in `v4.0.1` later today :)

**Comment by 4mig4** [comment]
I installed `4.0.1` but I am not seeing this fixed  in `index page`, I still see the `index` page rendered as I explain before in https://github.com/Fizzadar/Luapress/issues/75#issuecomment-509057641, however it seems to be the problem only when there is a `--MORE--` marker in the page.

I do not have the ability to mark this issue as `re-opened` though.

```
luapress
   4.0.1-0 (installed) - /usr/local/lib/luarocks/rocks-5.1
```
