### ISSUE TITLE
4.0.1 still exhibits same issue for $=toc

### ISSUE THREAD

**Issue by 4mig4** [Fizzadar/Luapress#77]
I installed 4.0.1 but I am not seeing this fixed in index page, I still see the index page rendered as I explain before in #75 (comment), however it seems to be the problem only when there is a --MORE-- marker in the page.

I do not have the ability to mark this issue as re-opened though.

luapress
   4.0.1-0 (installed) - /usr/local/lib/luarocks/rocks-5.1

**Comment by 4mig4** [comment]
I had posted this in the closed issue #75 and this is probably why you have not noticed it.

**Comment by Fizzadar** [comment]
@4mig4 this should be fixed by https://github.com/Fizzadar/Luapress/commit/26763e15031034e0f038bc2a9ceac7dbb846bd52.

**Comment by 4mig4** [comment]
So I just upgraded and tested Luapress 4.1 and for me it **does not** appear fixed , I still see in the Luapress **index page** `$=toc` showing instead of it being ignored and no displayed in the index page only. My headers are, like  the example of one of my Luapress `posts` :

```
$title=TEST
$date=32/08/2019
$location=Kyoto, Japan
$=toc

This is a test

--MORE--

Lorem Ipsum, Lorem Ispum
```

What I see in the **index page**  entry for this post is : 

```
$=toc

This is a test
```

**Comment by Fizzadar** [comment]
@4mig4 I've not released this yet so you'll need to install from the commit above - I've confirmed it's working with your post as above.

I'm hoping to get `4.1.1` released over the next few days which will include this fix.

**Comment by Fizzadar** [comment]
@4mig4 I've not released this yet so you'll need to install from the commit above - I've confirmed it's working with your post as above.

I'm hoping to get `4.1.1` released over the next few days which will include this fix.

**Comment by Fizzadar** [comment]
@4mig4 - change of plans I've just released `v4.1.1` :)
